CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    usertag VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL,
    status BOOLEAN NOT NULL DEFAULT TRUE,
    ban BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE links(
    id SERIAL PRIMARY KEY,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    url VARCHAR(2048) NOT NULL,
    embed VARCHAR(2048) NOT NULL DEFAULT FALSE,
    category_1 VARCHAR(20) NOT NULL,
    category_2 VARCHAR(20),
    category_3 VARCHAR(20),
    isMusic BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
)